# Config du plugin AzuriomSkinAPI

# L'URL de l'API Skin. N'oubliez pas de mettre {player} pour que le skin appliqué soit celui de chaque utilisateur.
skin_api_url: "https://votre-url.com/{player}"

#Define if you want to use ancient command ( before versions of SkinRestorer ) or no.
use-ancient-command: false

# Envoyer un message de succès au joueur quand le skin est changé automatiquement
send_success_message: true

# Message de succès (affiché au joueur quand le skin est changé)
success_message: "&aVotre skin a été mis à jour avec succès !"

# Envoyer des logs dans la console quand le skin est changé automatiquement
send_console_logs: true

# Message de force update
force_update_success_message: "&aLe skin de l'utilisateur à bien été changé !"

# Si le joueur spécifié n'est pas connecté 
no_player_connected: "&cLe joueur spécifié n'est actuellement pas connecté sur ce serveur."

# Ne pas toucher !!
version: 1.0
